version: '3'

services:
  postgres:
    image: postgres:12-alpine
    # network_mode: "host"
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:alpine
    # network_mode: "host"
  manager:
    image: massbit/manager
    ports:
      - '3000:3000'
    # network_mode: "host"
    depends_on:
      - "postgres"
      - "redis"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PROJECTS_DIR: ./projects
