version: '3'

services:
  graphql-engine:
    image: query
    network_mode: "host"
    restart: always
    environment:
      PORT: 3001
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: 127.0.0.1
      DB_POST: 5432
    command:
      - --name=account-balances
      - --playground