version: '3'

services:
  graphql-engine:
    image: massbit/query
    ports:
      - '3001:3001'
    # network_mode: "host"
    restart: always
    environment:
      PORT: 3001
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_POST: 5432
    command:
      - --name=account-balances
      - --playground

networks:
  default:
    external: true
    name: account-balances_default